default_config:
  repo_prefix: /hydra
  node_name: node1
  base_path: $HOME/.ndn
  data_storage_path: $HOME/.ndn/hydra/node1/data.db
  global_view_path: $HOME/.ndn/hydra/node1/global_view.db
  svs_storage_path: $HOME/.ndn/hydra/node1/svs.db
  logging_path: $HOME/.ndn/hydra/node1/session.log
  logger_level: INFO

  timers:
    loop_period: 5000
    tracker_rate: 25000
    heartbeat_rate: 20000
    beats_to_renew: 3
    beats_to_fail: 3
    replication_degree: 2
    file_expiration: 2 # in hours, 0 = never expire

  favor:  
    rtt: 0
    rw_speed: 0
    num_users: 0
    bandwidth: 0
    network_cost: 0
    storage_cost: 0
    remaining_storage: 0
