# When a pull request is merged into the main branch and includes "increment:major", "increment:minor", or "increment:patch" 
# in the commit message, or when you push directly to the main branch, the workflow will automatically run, incrementing the 
# version number accordingly and pushing the changes back to the repository.

name: Upload Python Package

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  determine-version:
    name: Determine Version Increment
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      increment: ${{ steps.get_version.outputs.increment }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Determine version increment
      id: get_version
      run: |
        # Extract commit messages
        messages=$(git log --format=%B -n 1 $GITHUB_SHA)
        
        # Set default increment
        increment="patch"
        
        # Determine increment based on commit messages
        if echo "$messages" | grep -q "increment:major"; then
          increment="major"
        elif echo "$messages" | grep -q "increment:minor"; then
          increment="minor"
        elif echo "$messages" | grep -q "increment:patch"; then
          increment="patch"
        fi
        
        echo "increment=$increment" >> $GITHUB_ENV
        
        # Get current version
        current_version=$(python setup.py --version)
        
        # Increment version
        new_version=$(python -c "import semver; print(semver.VersionInfo.parse('$current_version').bump_$increment())")
        
        echo "version=$new_version" >> $GITHUB_ENV
        echo "::set-output name=version::$new_version"
        echo "::set-output name=increment::$increment"

    - name: Update version in setup.py
      run: |
        sed -i "s/version=.*,/version='$VERSION',/" setup.py
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add setup.py
        git commit -m "Bump version to ${{ steps.get_version.outputs.version }}"
        git push origin main
